### ISSUE TITLE
refactor sound sensor simulator

### ISSUE THREAD

**Issue by nokacper24** [JakobHolkestadMolnes/IOT-Sound#13]
Clippy complains about this:
```
error: this `if` has identical blocks
  --> iot_sound_sensor/src/loudness_sensor_simulator.rs:54:35
   |
54 |           } else if self.state == 1 {
   |  ___________________________________^
55 | |             return self.day_loudness();
56 | |         } else {
   | |_________^
   |
```
maybe use `match` instead?  
Also make state an enum maybe? This will define a finite set of valid states.

**Comment by nokacper24** [comment]
still better to use `enum` and `match`

**Comment by julianmontague** [comment]
d299963f0118a972a9cc850d9b544f502b49d8ea messes up the state change code, clamping for day values after changing the state to night. I’ll fix it.
