### ISSUE TITLE
Simulate data output from the microphone

### ISSUE THREAD

**Issue by julianmontague** [JakobHolkestadMolnes/IOT-Sound#3]
Since we don't have the microphone(s) yet, we should write some code to simulate the output of the microphone in order to continue with the project.

**Comment by nokacper24** [comment]
foundation for the sensor node added in f3a22d8130bfe5ab33327a38304b3848f80c7f76  
function message_generator() can send simulated data to mqtt client

**Comment by nokacper24** [comment]
as of now `LoudnessSensorSimulator` returns totally random values, the data should instead create a more meaningful curve

**Comment by julianmontague** [comment]
I improved the random generation by making a random *change* each time in this commit: bad7208bd1ef64c1b20b964f592c03c876e88866

**Comment by julianmontague** [comment]
I added different simulation states (day and night) now: 0e67d98ffd8019061d87d0a054b6e26b589bc904
